all:
	pdflatex -output-directory=./guia-$(guia) ./guia-$(guia)/main.tex
	pdflatex -output-directory=./guia-$(guia) ./guia-$(guia)/main.tex
	pdflatex -output-directory=./guia-$(guia) ./guia-$(guia)/main.tex

clean:
	rm -f ./guia-$(guia)/main.pdf
	rm -f ./guia-$(guia)/main.aux
	rm -f ./guia-$(guia)/main.toc
	rm -f ./guia-$(guia)/main.log
